# version: '3'

# services:
#   mysql:
#     image: mariadb
#     volumes:
#       - /data/mysql:/var/lib/mariadb_mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: mysql_root_pass
#       MYSQL_DATABASE: db_name
#       MYSQL_USER: asgaulti
#       MYSQL_PASSWORD: asgaulti42
#     restart: always
#   wordpress:
#     image: wordpress:php7.3-fpm-alpine
#     volumes:
#       - /data/html:/var/www/html
#     depends_on:
#       - mysql
#     environment:
#       WORDPRESS_DB_HOST: mysql
#       MYSQL_ROOT_PASSWORD: mysql_root_pass
#       WORDPRESS_DB_NAME: db_name
#       WORDPRESS_DB_USER: asgaulti
#       WORDPRESS_DB_PASSWORD: asgaulti42
#       WORDPRESS_TABLE_PREFIX: wp_
#     links:
#       - mysql
#     restart: always
#   nginx:
#     image: nginx:alpine
#     volumes:
#       - ./nginx:/requirements/nginx/conf 
#       - ./data/html:/var/www/html
#     ports:
#       - 8080:80
#     links:
#       - wordpress

version : '3'

services:
  mysql:
    build:
      context: ./requirements/mysql
    # ports:
    # <host_port>:<container_port>
    # environment:
      # MYSQL_ROOT_PASSWORD: mysql_root_pass
      # MYSQL_DATABASE: db_name
      # MYSQL_USER: user_name
      # MYSQL_PASSWORD: user_pass
    # restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mysql # le service WP depend de mysql
    # environment:
    #   WORDPRESS_DB_HOST: mysql
    #   MYSQL_ROOT_PASSWORD: lol
    #   WORDPRESS_DB_NAME: wpwordpress
    #   WORDPRESS_DB_USER: root
    #   WORDPRESS_DB_PASSWORD: lol
    #   WORDPRESS_TABLE_PREFIX: wp_
    # links:
      # - mysql # permet au service WP de cmmuniquer avec mysql service
    # restart: always

  nginx:
    build:
      context: ./requirements/nginx
    # volumes:
    #   - ./nginx:/requirements/nginx/nginx.conf 
    #   - ./data/html:/var/www/html
      #- nginx:/etc/nginx/conf.d
      #- /data/html:/var/www/html
    ports:
      - 443:443
    # links:
    #   - wordpress #permet de communiquer avec le service mysql


# 3 services : nginx, WP + php-fpm, MariaDB
# un volume contenant bdd de WP
# un volume contenant fichiers du site WP
# un docker-network faisant le lien entre les containers (attention : host ou --link ou links interdits)