version : '3'

services :

	nginx :
		build: nginx:<version>
		container_name: <nginx>
		ports:
			- <443>:<443>
		depends_on:
			- <other_service>
		env_file:
			- <path_to_env_file>
		networks:
			- <network_name>
		restart: <restart_policy>

	<MariaDB>:
    build: <mariadb>:<version>
		container_name: <container_name (no seriously what suprise)>
		ports:
			- <host_port>:<container_port>
		depends_on:
			- <other_service>
		env_file:
			- <path_to_env_file>
		volumes:
			- <WP>:<path_in_container>
		restart: <restart_policy>

	<WordPress_PHP>:
    build: <WordPress_PHP>:<version>
		container_name: <container_name (no seriously what suprise)>
		ports:
			- <host_port>:<container_port>
		depends_on:
			- <other_service>
		env_file:
			- <path_to_env_file>
		volumes:
			- <DB>:<path_in_container>
		restart: <restart_policy>

networks:
	<network_name>:

volumes:
	<WP>:
		driver: local
		driver_opts:
			type: none
			device: <host_path>
			o: bind
	
	<DB>:
		driver: local
		driver_opts:
			type: none
			device: <host_path>
			o: bind

# 3 services : nginx, WP + php-fpm, MariaDB
# un volume contenant bdd de WP
# un volume contenant fichiers du site WP
# un docker-network faisant le lien entre les containers (attention : host ou --link ou links interdits)