version : '3'

services :

	MariaDB:
    image: mariadb
		volumes:
			- /requirements/mariadb:/var/lib/mysql #met le path de la machine hote dans le path du container
			#ainsi les db files seront stockes dans la machine hote
			
		container_name: MariaDB
		# ports:
		# <host_port>:<container_port>
		env_file:
			MYSQL_ROOT_PASSWORD: mysql_root_pass
			MYSQL_DATABASE: db_name
			MYSQL_USER: user_name
			MYSQL_PASSWORD: user_pass
		restart: always


# 3 services : nginx, WP + php-fpm, MariaDB
# un volume contenant bdd de WP
# un volume contenant fichiers du site WP
# un docker-network faisant le lien entre les containers (attention : host ou --link ou links interdits)