# installation php
RUN apt-get -y install php7.3 php7.3-fpm php7.3-common php7.3-mysql php7.3-curl php7.3-intl php7.3-mbstring php7.3-cli php7.3-soap php7.3-imap

# sudo userdel www-data
# sudo useradd -u 82 www-data

# sudo mkdir -p /data/html
# sudo chown -R www-data:www-data /data/html