#installation nginx
RUN apt-get -y install nginx

# rm /etc/nginx/sites-available/default
# rm /etc/nginx/sites-enabled/default
rm /var/www/html/index.nginx-debian.html
# ln -s /etc/nginx/sites-available/localhost /etc/nginx/sites-enabled/
